### ISSUE TITLE
Achievement Repo Incorrect Rewards

### ISSUE THREAD

**Issue by Corbeno** [BigCoight/IdleonWikiBot3.0#11]
The following commit https://github.com/BigCoight/IdleonWikiBot3.0/commit/218e162f1f611b817a17cfe3aa431b4588b3733b changed a few of the "rewards" fields in exported/list/Misc/AchievementRepo.json. I think this is caused by incorrect splitting by commas in the description.

**Comment by BigCoight** [comment]
Should be fixed now, thank you for poiting this out
