### ISSUE TITLE
Tool upgrade stones show weapon power

### ISSUE THREAD

**Issue by Corbeno** [BigCoight/IdleonWikiBot3.0#19]
For example: 
![image](https://user-images.githubusercontent.com/15672485/235416786-e4e16d7a-4cd1-4f42-a592-be0a201499a6.png)

Shows up as:
![image](https://user-images.githubusercontent.com/15672485/235416844-5ca22d9a-582b-4c40-bf3d-5f269652aa50.png)

In SpecificItemRepo.json

**Comment by BigCoight** [comment]
Fixed!
