### ISSUE TITLE
Trapper drone maxLvl should be increased to 50

### ISSUE THREAD

**Issue by Corbeno** [BigCoight/IdleonWikiBot3.0#20]
Construct mastery made this possible
![image](https://github.com/BigCoight/IdleonWikiBot3.0/assets/15672485/3c7ecd4e-f1c3-4151-b0a6-a3a981e9a3c6)

maxLevel should be bumped up to 50 now
![image](https://github.com/BigCoight/IdleonWikiBot3.0/assets/15672485/90df6d65-a3dd-4483-8719-c4e6643e1f1e)

**Comment by Sludging** [comment]
Conditional code never goes into the wiki, i.e. the max level is only true IF you unlocked that so it should be done in the "consumer" code and not here.

Also if you notice `misc` now shows the max potential level of all buildings so that info is actually there already just mislabeled.
